---
title: "Wish Kid Graph Draft 1"
output: html_document
date: "2023-04-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(ggplot2)
```

```{r}
data2 <-  read.csv("wishkid_data.csv") 
data3 <- read.csv("survey.csv")

View(data2)
View(data3)


head(data2) # Loads a few rows and columns of the dataset
head(data3)
sapply(data2, class) # Let's examine the classes of all the variables we are working with
sapply(data3, class)
```

Months between qualified data and actual data 

```{r}

# Create a new column that calculates the number of months between the Actual Wish Date and the Qualified Date
data2$Actual.Wish.Date <- as.Date(data2$Actual.Wish.Date, format = "%m/%d/%Y")
data2$Qualified.Date <- as.Date(data2$Qualified.Date, format = "%m/%d/%Y")

# data2$months <- as.numeric(difftime(data2$Actual.Wish.Date, data2$Qualified.Date, units = "weeks"))/4
data2$months <- as.numeric(difftime(data2$Actual.Wish.Date, data2$Qualified.Date, units = "weeks"))/4


hist(data2$months, breaks = 20, col = "#8ABD91", main = "Number of Months between Qualified Date and Actual Wish Date", xlab = "Months")


```



